<?php

namespace Cancino\FormularioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProdFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdFormRepository extends EntityRepository
{
}
