doc_rel:
    resource: "@DocRelBundle/Resources/config/routing.yml"
    prefix:   /

cancino_formulario:
    resource: "@CancinoFormularioBundle/Resources/config/routing.yml"
    prefix:   /

curso_main:
    resource: "@CursoMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
