<?php

namespace Curso\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends EntityRepository
{
	public function listarId($id) {
		$em=$this->getEntityManager();
		$dql="select a from CursoMainBundle:Articles a where a.id=:id";
		$query=$em->createQuery($dql);
		$query->setParameter('id',$id);
		$com=$query->getResult();
		return $com;
	}
}
